baseurl: ""
url: "https://longern.com"
remote_theme: mmistakes/minimal-mistakes@4.13.0
title: "Longern"
author: Longern
logo: https://longern.com/static/img/avatar.png
github: https://github.com/longern

plugins:
  - jekyll-sitemap
include:
  - _nuxt

disqus_shortname: longern
google_analytics: UA-133314683-1

paginate: 10
